### ISSUE TITLE
Add support for Godot 4.0

### ISSUE THREAD

**Issue by ceceppa** [ceceppa/anima#13]

**Comment by middlepattern** [comment]
Works now. Thank you for the fix.

**Comment by hakuhan** [comment]
It is not working in alpha 10.

**Comment by ceceppa** [comment]
Hi,
I'll be releasing next week the first official version for Godot 4.

**Comment by hakuhan** [comment]
Oh, So nice! Got it.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ceceppa** [comment]
The first WIP version is available on the `https://github.com/ceceppa/anima/tree/godot-4` branch. So far, almost everything seems working fine.
There is an issue with Loops that I'll try to fix in the next days

**Comment by ceceppa** [comment]
Here the first unstable version of the addon-on for Godot4: https://github.com/ceceppa/anima-godot-4

**Comment by middlepattern** [comment]
Thanks for your continued work on this!

**Comment by cyberpsyche** [comment]
Hi @ceceppa , thanks for your porting of this repo to godot4.  I've tried out your anima-godot-4 addon in Godot4 (alpha, beta, stable, master branch ...) for months. Many features work fine in Godot4, but some pre-defined animations cannot be executed in godot new version 4, such as "Bounce In Left/Right", "Fade in/out", etc. ... 

As anima is such a good tool I will never give up to use, I wonder if you are still in the working progress on this project? 
 I noticed that you are not update anima-godot-4 repo frequently. Hoping you could keep polishing anima addon in Godot4. Hoping to see the stable version of anima-godot-4 as soon as possible .  

Thank you again on behalf of so many anima users.  :) 👍

**Comment by ceceppa** [comment]
Hi,
I'm planning to fix all the broken animations this weekend. I'll update this ticket once completed

**Comment by cyberpsyche** [comment]
@ceceppa  Awesome! Looking forward to your update.    :)

Thanks!

**Comment by ceceppa** [comment]
@cyberpsyche, all the animations should work fine now. There is some bug around reversing animations, which should be fixed soon.
I've uploaded the `anima-godot-4` repo and also submit to the assets library, so once approved you'll be able to install/update from Godot itself :)

**Comment by cyberpsyche** [comment]
@ceceppa , Great news for this week ！Thank you for your quick update , I'll try your new repo.  👍

**Comment by ceceppa** [comment]
@cyberpsyche the addon is now also available on the Assets library: https://godotengine.org/asset-library/asset/1842

**Comment by cyberpsyche** [comment]
Thanks @ceceppa , your new repo runs well on Godot 4.0.X. Nice job ! 👍
