### ISSUE TITLE
Can't run anima - project.gd broken

### ISSUE THREAD

**Issue by BenHerbst** [ceceppa/anima#16]
After trying to activate Anima in Godot, the editor says: "Can't activate Shape plugin, broken project.gd"

**Comment by BenHerbst** [comment]
I think it is because I use Godot 3.4 and Ceccepa 3.3.4 as I saw in a Video

**Comment by BenHerbst** [comment]
![image](https://user-images.githubusercontent.com/83538916/146611943-d2dccd16-0642-48c7-bc31-214685777073.png)

**Comment by middlepattern** [comment]
Having same issue.

**Comment by ceceppa** [comment]
@BenHerbst @middlepattern I just pushed a fix for this. Mind double-checking?

**Comment by BenHerbst** [comment]
@ceceppa I did git pull and it works now. But the Visual Editor is too big scaled.
Screenshot:
![image](https://user-images.githubusercontent.com/83538916/147348740-5c1bf854-96e3-40a6-acd7-fe1df6a9f587.png)
How can I scale it down?
