### ISSUE TITLE
Too big visual editor size

### ISSUE THREAD

**Issue by BenHerbst** [ceceppa/anima#17]
![image](https://user-images.githubusercontent.com/83538916/147349103-c4f17514-cea4-4076-b288-791e43fee110.png)
Scale the default UI size down, as all buttons are too big.

**Comment by BenHerbst** [comment]
Found out that the font size is too big on Windows, maybe change it together with screen dpi?

**Comment by ceceppa** [comment]
This now has been fixed

**Comment by BenHerbst** [comment]
Good
