### ISSUE TITLE
Error when trying to play an animation

### ISSUE THREAD

**Issue by zakstam** [ceceppa/anima#19]
I'm not sure if thats intentional but the `pivot` is passed as a string there and the function expects a dictionary:
![image](https://user-images.githubusercontent.com/1850856/148539246-f350e623-2796-4e2c-b40c-1aefc2dd443b.png)
![image](https://user-images.githubusercontent.com/1850856/148539292-3d44490a-873d-490e-8f01-e9e712ccf6d1.png)
![image](https://user-images.githubusercontent.com/1850856/148540436-eea430f3-52c1-45ca-b714-4e93ad1e628b.png)

The code that invoked the error:
```GDScript
var anima := Anima.begin(self)
anima.then({node = self, animation = "tada", duration = 0.7})
anima.play()
```
The object (self) is a MarginContainer if that helps.

**Comment by ceceppa** [comment]
Which version of the plugin are you using? the `master` branch or the one from the Godot assets store?

**Comment by zakstam** [comment]
![image](https://user-images.githubusercontent.com/1850856/148545293-aadb7785-172f-488f-98c6-fca7df4bf6ea.png)

**Comment by zakstam** [comment]
> Which version of the plugin are you using? the `master` branch or the one from the Godot assets store?

I actually tried both. The one from the asset store doesn't even appear in the plugins list

**Comment by zakstam** [comment]
The error only seems to happen with `tada` animation btw

**Comment by ceceppa** [comment]
Fixed! Thanks for the report :)
