### ISSUE TITLE
Hide strategy proposal and a bug report

### ISSUE THREAD

**Issue by zakstam** [ceceppa/anima#20]
[PROPOSAL] Although the [hide strategy](https://anima.ceceppa.me/doc/anima-node.html#hide-strategy) is nice and in most cases more than enough, there are times where i would prefer for example to have an initial value for position or size instead of visibility or transparency.
An interesting solution would be to have an additional property `initial_value` which sets all the nodes to the value before the animation begins. Of course all of this could be done manually (setting the size of the nodes before the animation starts for example) but since anima already iterates through the objects it would be convenient if there was a built in property.

[BUG] Also when using `anima.set_visibility_strategy(Anima.VISIBILITY.TRANSPARENT_ONLY)` with a group animation the changes the `scale` of the controls, the controls never came back to be visible. I would expect them to become visible once the animation starts. I had to animate modulate to overcome this:
```GDScript
anima.with({
  group = games_container,
  items_delay = 0.05,
  property = "modulate:a",
  from = 0,
  to = 1
})
```

**Comment by ceceppa** [comment]
I like the proposal.
For `initial_value` I assume will be set the same property you're trying to animate, right?

For the BUGS things might be a bit broken in master, I'll check and fix ASAP :)

**Comment by zakstam** [comment]
> I like the proposal. For `initial_value` I assume will be set the same property you're trying to animate, right?
> 
> For the BUGS things might be a bit broken in master, I'll check and fix ASAP :)

Yup, if you are animating `scale` for example then the `initial_value` would be a `Vector2()`
An example would be:
```GDScript
anima.then({
	group = $Group,
	items_delay = 0.05,
	property = "position:x",
        initial_value = 0,
	from = -1500,
	to = 0,
	easing = Anima.EASING.EASE_OUT_SINE,
	})
```
Or
```GDScript
anima.then({
	group = $Group,
	items_delay = 0.05,
	property = "scale",
        initial_value = Vector2(0, 0),
	from = -1500,
	to = 0,
	easing = Anima.EASING.EASE_OUT_SINE,
	})
```

**Comment by ceceppa** [comment]
An initial implementation of "initial_value" has been pushed

**Comment by ceceppa** [comment]
This has now be fully implemented
