### ISSUE TITLE
Structure proposal

### ISSUE THREAD

**Issue by zakstam** [ceceppa/anima#21]
You seem to be using the same class (`AnimaNode`) for everything right but this makes it hard to maintain and possibly prone to errors because you have to pass dictionaries with properties that sometimes are not compatible with each other. Plus users will have to remember all the names of the properties they have to pass. A better approach would be to have a different class for each type of animation. An example would be:
```GDScript
# Create a class named AnimaAnimationGrid (or something similar)
# then pass the type of the animation into the Begin method so this would return an AnimaAnimationGrid node instead of a generic AnimaNode.
# With that in place now you can have proper properties for the methods instead of dictionaries (kind of like tween but with all of the nice features your project provieds)
var anima := Anima.Begin(AnimaAnimations.Grid, self)
anima.then(
   grid: $Grid,
   grid_size: grid_size,
   animation_type: Anima.GRID.COLUMNS_EVEN,
   property: "x",
   to: 5, 
   relative: true,
   duration: 0.3,
   easing: Anima.EASING.EASE_OUT_SINE,
   items_delay: 0
)
```

That way users wont have to go back to the documentation in order to check which parameters they can pass etc...

EDIT: And of course have a base class from which all of the animations inherit

**Comment by ceceppa** [comment]
I think it would be impossible to mix different animations, such as `animating a single node and a group` using the same Anima.

Also, I did avoid on purpose parameters and preferred a Dictionary because Godot does not support named parameters, and you have to pass all the parameters, even if not used.

Said that we could use a different syntax that is more dev friendly, for example:

```gdscript
var anima := Anima.begin(self)

anima.then(
	Anima.Node($Control) \
	.anima_property("position") \
	.anima_duration(0.3)
)

anima.then(
	Anima.Grid($Grid) \
	.anima_grid_size(Vector2(3, 2))
)
```

The `then`, `with` and `also` function will accept one of the following classes:

- Anima.Node - to animate a single node
- Anima.Group - to animate a group of nodes
- Anima.Grid - to animate a grid of nodes

By doing so, the editor will **only** show you the methods that exist for the type of Animation you're creating. 
Also, the prefix `anima_` helps to filter out all the default class methods and properties:

<img width="419" alt="Screenshot 2022-01-07 at 15 23 39" src="https://user-images.githubusercontent.com/6877714/148571226-5b76c977-a5c0-4713-bfd0-88fbcf4ebb5f.png">

**Comment by Terria-K** [comment]
> You seem to be using the same class (`AnimaNode`) for everything right but this makes it hard to maintain and possibly prone to errors because you have to pass dictionaries with properties that sometimes are not compatible with each other. Plus users will have to remember all the names of the properties they have to pass. A better approach would be to have a different class for each type of animation. An example would be:
> 
> ```gdscript
> # Create a class named AnimaAnimationGrid (or something similar)
> # then pass the type of the animation into the Begin method so this would return an AnimaAnimationGrid node instead of a generic AnimaNode.
> # With that in place now you can have proper properties for the methods instead of dictionaries (kind of like tween but with all of the nice features your project provieds)
> var anima := Anima.Begin(AnimaAnimations.Grid, self)
> anima.then(
>    grid: $Grid,
>    grid_size: grid_size,
>    animation_type: Anima.GRID.COLUMNS_EVEN,
>    property: "x",
>    to: 5, 
>    relative: true,
>    duration: 0.3,
>    easing: Anima.EASING.EASE_OUT_SINE,
>    items_delay: 0
> )
> ```
> 
> That way users wont have to go back to the documentation in order to check which parameters they can pass etc...
> 
> EDIT: And of course have a base class from which all of the animations inherit

This kind of style syntax isn't possible with GDScript yet.. as GDScript doesn't support Structs. This only be possible in C# as it has a structs. Yes, I agree about hard to maintain a property and had to look on the documentation, but there are many parameters that this addon has in just one function.

**Comment by Terria-K** [comment]
> I think it would be impossible to mix different animations, such as `animating a single node and a group` using the same Anima.
> 
> Also, I did avoid on purpose parameters and preferred a Dictionary because Godot does not support named parameters, and you have to pass all the parameters, even if not used.
> 
> Said that we could use a different syntax that is more dev friendly, for example:
> 
> ```gdscript
> var anima := Anima.begin(self)
> 
> anima.then(
> 	Anima.Node($Control) \
> 	.anima_property("position") \
> 	.anima_duration(0.3)
> )
> 
> anima.then(
> 	Anima.Grid($Grid) \
> 	.anima_grid_size(Vector2(3, 2))
> )
> ```
> 
> The `then`, `with` and `also` function will accept one of the following classes:
> 
> * Anima.Node - to animate a single node
> * Anima.Group - to animate a group of nodes
> * Anima.Grid - to animate a grid of nodes
> 
> By doing so, the editor will **only** show you the methods that exist for the type of Animation you're creating. Also, the prefix `anima_` helps to filter out all the default class methods and properties:
> 
> <img alt="Screenshot 2022-01-07 at 15 23 39" width="419" src="https://user-images.githubusercontent.com/6877714/148571226-5b76c977-a5c0-4713-bfd0-88fbcf4ebb5f.png">

I think this is great, maybe if it's possible to not have a prefix?

**Comment by ceceppa** [comment]
Yeah, I was thinking of the prefix only because the autocomplete shows too many options by default.
Happy to don't have it :)

**Comment by Terria-K** [comment]
> Yeah, I was thinking of the prefix only because the autocomplete shows too many options by default. Happy to don't have it :)

Oh.. it seems prefix will be a good idea then. You could let that stay instead.

**Comment by ceceppa** [comment]
I've pushed an initial implementation for this. The `then` and `with` methods now accept a class as a parameter, and the built-in ones are:

- Anima.Node
- Anima.Group
- Anima.Grid

Possible to pass a dictionary is still possible tho
