### ISSUE TITLE
GLES3 causes lockup for 30-45 seconds in the 3d demos

### ISSUE THREAD

**Issue by tavurth** [ceceppa/anima#26]
Please see this relevant Godot issue:

https://github.com/godotengine/godot/issues/56670

Perhaps we could move to GLES2 export for the demo example to prevent issues with GLES3 shader compilation?

**Comment by ceceppa** [comment]
Hi, Thanks for the report.
I wasn't aware of this issue, I'll re-export the demos using GLES2 and update the website later today :)
