### ISSUE TITLE
Translations not working as expected on typewrite animation

### ISSUE THREAD

**Issue by JPCard** [ceceppa/anima#27]
Hi, I found out that typewrite is currently using 
`var l = node.text.length()`
this leads to getting translation key length instead of the actual translation text leght.
In order to fix the issue I changed that line to 
`var l = tr(node.text).length()`
so it now uses translation resolved text instead of translation key and it is fully compatible with non translated Strings.

I was going to open a PR with the fix but I found out that typewrite sintax changed on your latest version and I don't know how to properly invoke tr function on that case.

**Comment by ceceppa** [comment]
Hi, thanks for the report; I've changed the implementation to use `tr`:

https://github.com/ceceppa/anima/blob/main/addons/anima/utils/node_properties.gd#L150
