### ISSUE TITLE
Not Support shader_param?

### ISSUE THREAD

**Issue by DSPerson** [ceceppa/anima#30]
godot: 3.5.1
anima: 0.3.2
I found shader_param in doc is error. use `shared_param`?
```
var anima = Anima.begin(self, 'al2')
anima.then({node = $Sprite, property = "material:shader_param/DissolveRate", from = -1.0, to = 1.0, duration = 1})
anima.then({node = self, property = "opacity", from = 1, to = 0, duration = 0.28})
anima.play()
```
but not work

<img width="374" alt="image" src="https://user-images.githubusercontent.com/17868782/204119348-f2cc072f-59cd-4e60-aefb-d8cf3a79cbcd.png">

then I used Tween, luckily is correct

```
var t = $Sprite/Tween.interpolate_property($Sprite, "material:shader_param/DissolveRate", -1, 1, 1)
$Sprite/Tween.start()
```

**Comment by ceceppa** [comment]
Hi, 
yes, that's a typo in the doc and I'll fix it. In your case you need to use `shader_param:DissolveRate`, i.e.:

```
var anima = Anima.begin(self, 'al2')
anima.then({node = $Sprite, property = "shader_param:DissolveRate", from = -1.0, to = 1.0, duration = 1})
anima.then({node = self, property = "opacity", from = 1, to = 0, duration = 0.28})
anima.play()
```

The syntax is slightly different from the Godot one

**Comment by DSPerson** [comment]
That code run in Godot not error.
Unfortunately,  not work.

**Comment by DSPerson** [comment]
I found reason, my shader param name is `DissolveRate`, but in you anima code 

```
static func get_property_initial_value(node: Node, property: String):
	property = property.to_lower()
...
```
you set property lower, I am a beginner,  is it a code specification?
😁

**Comment by ceceppa** [comment]
uhm, yeah that code no longer exists in the main branch, probably for the same reason 😓 . You could try to use the addon from this repo instead of the one from the asset library, while I complete all the documentation
