### ISSUE TITLE
anima_property cannot handle discontinuous property eg. bool property

### ISSUE THREAD

**Issue by hakuhan** [ceceppa/anima#37]
Hi!
    When I tried to call anima_property func with "visible" value.  Script will be broken at runtime. I tried to use callback func to set visibility(It is not a straight forward solution).
![image](https://github.com/ceceppa/anima/assets/18411187/29eec3cc-c4bc-4625-91aa-4f5608cd9e90)
![image](https://github.com/ceceppa/anima/assets/18411187/cf7fb439-68c2-4790-9ef6-0b2795a05fbc)
If you have any idea to solve this little problem. Please let me know. Thanks!

**Comment by ceceppa** [comment]
Yes, animating a boolean is not supported. What are you trying to achieve? What kind of animation do you want to create?

**Comment by hakuhan** [comment]
Hi! Thanks for relay! I want create a flicker effect.

________________________________

**Comment by ceceppa** [comment]
So, you can animate the opacity instead. Maybe the built-in "Flash" animation is what are you looking for?

```
Anima.node(self).anima_animation('flash').play()
```
