### ISSUE TITLE
anima docs website was unavailable

### ISSUE THREAD

**Issue by LoserFox** [ceceppa/anima#39]
the docs and demos website see like been unavailable.
i can't make sure about it. but please to check. thanks.

**Comment by ceceppa** [comment]
Hi, the documentation has been moved here: https://ceceppa.github.io/anima/

**Comment by LoserFox** [comment]
> Hi, the documentation has been moved here: https://ceceppa.github.io/anima/

thanks! but link on the readme still was unchanged.

**Comment by ceceppa** [comment]
Fixed, thanks :)
