### ISSUE TITLE
just don't work, even the demo project

### ISSUE THREAD

**Issue by alexribeirodesa** [ceceppa/anima#41]
first of all, I recently migrated from Unity to Godot, so it could be something I'm doing wrong, but absolutely nothing works, not even importing it into my project or using the demo project.

this is the error when I try to import in my project:
`
  res://addons/anima/core/anima_node.gd:538 - Parse Error: Identifier "ANIMA" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/anima/core/anima_node.gd" with error "Parse error". (User)
`

this is the error when I try to run the demo project, and the godot build I'm using:
![image](https://github.com/ceceppa/anima/assets/2172704/2a20fe2b-6003-4a1e-bb8f-1ba2a18bcfcc)

thanks :)

**Comment by quimnuss** [comment]
Did you activate the plugin in settings?

**Comment by alexribeirodesa** [comment]
> Did you activate the plugin in settings?

yep :(

**Comment by quimnuss** [comment]
So I tried the plugin the rellevant error is the one on the screenshot not the one you pasted.

Apparently anima violates type enforcing of inheritance, since the parent does not specify the returned type but the children does.

A workaround is to just drop the typing (aka `-> AnimaDeclarationForProperty`)

```gdscript
func anima_from(value):
    super.anima_from(value)

    return self
```

**Comment by quimnuss** [comment]
The documentation isn't working and what I could find is outdated. But looking at the code, the following works, as an example:

```gdscript
extends Label

func _ready():
    var anima = Anima.New(self).anima_fade_in(10)

    anima.play()
```

I had to rename the function Node() to New() because it clashes with the Node type, here: https://github.com/ceceppa/anima/blob/main/addons/anima/core/anima.gd#L32

**Comment by ceceppa** [comment]
Sorry for getting back to you late. I just set up the auto-update thing for the docs and add-ons whenever the repo gets a push. Right now, I'm poking around to see if any links in the docs are busted, so it might take a little while to get it all smooth and working.

By the way, what version of the plugin and Godot are you on? If you're using Godot 4, please try and download the addon from here: https://github.com/ceceppa/anima-godot-4/

**Comment by quimnuss** [comment]
I don't know about alex, but me I used the AssetLibrary to add the anima addon. Anima for godot 4, version 0.5, whose view files points to the repo you posted.

**Comment by quimnuss** [comment]
Yeah maybe the Node() I changed to workaround the type clash issue was actually from anima-godot-4 not anima.  https://github.com/ceceppa/anima-godot-4/blob/main/addons/anima/core/anima.gd#L32

**Comment by ceceppa** [comment]
This has now been fixed. Everything should work fine with Godot 4.2 and Godot 4.3.

Please reopen if its not the case
