### ISSUE TITLE
Error on project startup

### ISSUE THREAD

**Issue by 40-4** [ceceppa/anima#46]
Everytime I start my project which is using Anima, i get this two errors:

```
scene/resources/resource_format_text.cpp:453 - res://addons/anima/ui/AnimationPicker/HeaderButton.tscn:3 - ext_resource, invalid UID: uid://bbwti30umytri - using text path instead: res://addons/anima/icons/Closed.svg
scene/resources/resource_format_text.cpp:453 - res://addons/anima/ui/AnimationPicker/AnimationPicker.tscn:5 - ext_resource, invalid UID: uid://ca72ljjcye5v1 - using text path instead: res://addons/anima/resources/anima-preview.png
```

Is there something i could do to get rid of them? I doesnt really want to modify the plugin I don't yet understand well, so I'm asking here for help.

**Comment by 40-4** [comment]
okay, after downloading the version from asset library and changing one imago to the exact same image errors went away

**Comment by ceceppa** [comment]
I'll be removing the entire `ui` folder in the next updates as is not actually used anyway :)
