### ISSUE TITLE
Cyclic dependecy on editor?

### ISSUE THREAD

**Issue by AnidemDex** [ceceppa/anima#5]
Anima plugin works well inside the game. But some features to code with anima inside the editor are lost the first time you add the plugin (like autocompletion until the script is fully loaded by the editor).

For now, i discover that reloading the engine at least 2 times solves this (the first time you add the plugin folder and the second time after you activate the plugin)
![image](https://user-images.githubusercontent.com/7025991/108746842-d6468280-750a-11eb-8085-f008a95deff9.png)

**Comment by ceceppa** [comment]
Thanks, I'll investigate

**Comment by ceceppa** [comment]
This is fixed in master
